```py
fig1.update_traces(
    ### Make a coloured outline around the bars (in the case of a barplot)
    marker_line_color = 'red',
    marker_line_width=3
)

update_layout(
    xaxis_title="Date", 
    yaxis_title="7 day avg"
)
```

# sample datasets

In [1]:
import plotly.express as px

long_df = px.data.medals_long()
long_df

        nation   medal  count
0  South Korea    gold     24
1        China    gold     10
2       Canada    gold      9
3  South Korea  silver     13
4        China  silver     15
5       Canada  silver     12
6  South Korea  bronze     11
7        China  bronze      8
8       Canada  bronze     12

# bar

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import plotly.express as px

data = np.array([
    ['January', 50, 10],
    ['February', 50, 20],
    ['March', 40, 30]
])
df = pd.DataFrame({
    'month': data[:,0],
    'value1': data[:,1],
    'value2': data[:,2]
})
display(df)

df2 = pd.melt(df, id_vars=['month'], value_vars=['value1', 'value2'])
display(df2)

fig = px.bar(df2, x='month', y='value', color='variable')
fig.show()

      month value1 value2
0   January     50     10
1  February     50     20
2     March     40     30

      month variable value
0   January   value1    50
1  February   value1    50
2     March   value1    40
3   January   value2    10
4  February   value2    20
5     March   value2    30

In [3]:
fig = px.bar(df2, x='value', y='month', color='variable')
fig.show()

# Pie chart

In [14]:
df = px.data.gapminder().query("year == 2007").query("continent == 'Americas'")
print(df['country'].unique())

df = df[df['country'].isin([
    'United States', 'Brazil', 'Mexico', 'Colombia', 
    'Argentina', 'Canada', 'Chile', 'Uruguay', 'Venezuela',
    'Puerto Rico', 'Peru', 'Panama'
])]

['Argentina' 'Bolivia' 'Brazil' 'Canada' 'Chile' 'Colombia' 'Costa Rica'
 'Cuba' 'Dominican Republic' 'Ecuador' 'El Salvador' 'Guatemala' 'Haiti'
 'Honduras' 'Jamaica' 'Mexico' 'Nicaragua' 'Panama' 'Paraguay' 'Peru'
 'Puerto Rico' 'Trinidad and Tobago' 'United States' 'Uruguay' 'Venezuela']

In [2]:
!pip install plotly

Defaulting to user installation because normal site-packages is not writeable
Collecting plotly
  Downloading plotly-6.0.0-py3-none-any.whl.metadata (5.6 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-1.24.1-py3-none-any.whl.metadata (10.0 kB)
Requirement already satisfied: packaging in c:\users\evgeni zorin\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from plotly) (24.1)
Downloading plotly-6.0.0-py3-none-any.whl (14.8 MB)
   ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/14.8 MB 5.6 MB/s eta 0:00:03
   ---------------- ----------------------- 6.0/14.8 MB 20.5 MB/s eta 0:00:01
   ---------------------------------------  14.7/14.8 MB 31.8 MB/s eta 0:00:01
   ---------------------------------------- 14.8/14.8 MB 29.1 MB/s eta 0:00:00
Downloading narwhals-1.24.1-py3-none-any.whl (309 kB)
Installing collected packages: narwhals, plotly
Successfully installed narwhals-1.24.1 plotly-6.0.0

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: C:\Users\Evgeni Zorin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import plotly.express as px

fig = px.pie(df, values='pop', names='country',
             title='Population of American continent',
             hover_data=['lifeExp'], labels={'lifeExp':'life expectancy'})
fig.update_traces(
    textposition='outside',
    textinfo='percent+label+value'
)

fig.show()

NameError: name 'df' is not defined

In [22]:
import pandas as pd
import plotly.express as px

fig = px.pie(df, values='pop', names='country',
             title='Population of American continent',
             hover_data=['lifeExp'], labels={'lifeExp':'life expectancy'})
fig.update_traces(
    textposition='inside', 
    textinfo='percent+label'
)
"""
The line below hides labels inside of the pie chart if the area is too small:
https://plotly.com/python/pie-charts/?_gl=1*1ftxf7x*_gcl_au*NTQ2MTY1NjY4LjE3MTY0Mjk0NjE.*_ga*MTg1MzEwMjY5MC4xNzA4NDc5MzA5*_ga_6G7EE0JNSC*MTcyMTAwNzkzNS42OS4xLjE3MjEwMDg2MjcuNTEuMC4w#controlling-text-fontsize-with-uniformtext
"""
fig.update_layout(
    uniformtext_minsize=12, 
    uniformtext_mode='hide'
    )

margins = 100
fig.update_layout(
    showlegend=False, # Remove legend
    margin=dict(t=margins, b=margins, l=margins, r=margins) # make the pie chart bigger by reducing the margins
)

fig.show()